CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Уникальный идентификатор пользователя (int)
    phone VARCHAR(20) UNIQUE NOT NULL, -- Номер телефона как основной идентификатор
    username VARCHAR(50) UNIQUE, -- @username для поиска и ссылок
    display_name VARCHAR(100) NOT NULL, -- Имя для отображения
    bio TEXT, -- "О себе"
    avatar_url TEXT, -- Ссылка на аватар в S3/облаке
    last_seen_at TIMESTAMPTZ DEFAULT NOW(), -- Время последней активности
    settings JSONB DEFAULT '{}', -- Гибкое поле для настроек (тема, уведомления и т.д.)
    created_at TIMESTAMPTZ DEFAULT NOW(),
    deleted_at TIMESTAMPTZ NULL -- Мягкое удаление (аккаунт деактивирован)
);

-- Индексы для быстрого поиска
CREATE INDEX idx_users_phone ON users(phone);
CREATE INDEX idx_users_username ON users(username);
CREATE INDEX idx_users_display_name_trgm ON users USING GIN (display_name gin_trgm_ops); -- Для поиска по части имени
CREATE INDEX idx_users_last_seen ON users(last_seen_at);