// <auto-generated />
using System;
using API.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20260325132956_AddUserPasswordHash")]
    partial class AddUserPasswordHash
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("API.Infrastructure.Persistence.Entities.ChatEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<short>("ChatType")
                        .HasColumnType("smallint")
                        .HasColumnName("chat_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<long?>("LastMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("last_message_id");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("ChatType");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("chats", null, t =>
                        {
                            t.HasCheckConstraint("CK_chats_chat_type", "chat_type IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("API.Infrastructure.Persistence.Entities.ChatMemberEntity", b =>
                {
                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<bool>("IsPinned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_pinned");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long?>("LastReadMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("last_read_message_id");

                    b.Property<DateTimeOffset?>("LeftAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("left_at");

                    b.Property<DateTimeOffset?>("MuteUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("mute_until");

                    b.Property<short>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("role");

                    b.HasKey("ChatId", "UserId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_chat_members_user_id_active")
                        .HasFilter("left_at IS NULL");

                    b.HasIndex("ChatId", "UserId");

                    b.HasIndex("UserId", "ChatId");

                    b.ToTable("chat_members", null, t =>
                        {
                            t.HasCheckConstraint("CK_chat_members_role", "role IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("API.Infrastructure.Persistence.Entities.MessageContentEntity", b =>
                {
                    b.Property<long>("MessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("message_id");

                    b.Property<string>("EmojiPayload")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("emoji_payload")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("Entities")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("entities")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("MessageId");

                    b.ToTable("message_content", null, t =>
                        {
                            t.HasCheckConstraint("CK_message_content_not_empty", "COALESCE(LENGTH(TRIM(text)), 0) > 0 OR JSONB_ARRAY_LENGTH(emoji_payload) > 0");
                        });
                });

            modelBuilder.Entity("API.Infrastructure.Persistence.Entities.MessageEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset?>("EditedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("edited_at");

                    b.Property<short>("MessageType")
                        .HasColumnType("smallint")
                        .HasColumnName("message_type");

                    b.Property<long?>("ReplyToMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("reply_to_message_id");

                    b.Property<int>("SenderUserId")
                        .HasColumnType("integer")
                        .HasColumnName("sender_user_id");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ReplyToMessageId")
                        .HasFilter("reply_to_message_id IS NOT NULL");

                    b.HasIndex("SenderUserId");

                    b.HasIndex("ChatId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_messages_chat_id_created_at_not_deleted")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("ChatId", "CreatedAt", "Id")
                        .IsDescending(false, true, true);

                    b.ToTable("messages", null, t =>
                        {
                            t.HasCheckConstraint("CK_messages_message_type", "message_type IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("API.Infrastructure.Persistence.Entities.MessageReadEntity", b =>
                {
                    b.Property<long>("MessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("message_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("ReadAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("MessageId", "UserId");

                    b.HasIndex("MessageId");

                    b.HasIndex("UserId", "ReadAt")
                        .IsDescending(false, true);

                    b.ToTable("message_reads", (string)null);
                });

            modelBuilder.Entity("API.Infrastructure.Persistence.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Settings")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("settings")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName");

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("API.Infrastructure.Persistence.Entities.ChatEntity", b =>
                {
                    b.HasOne("API.Infrastructure.Persistence.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("API.Infrastructure.Persistence.Entities.ChatMemberEntity", b =>
                {
                    b.HasOne("API.Infrastructure.Persistence.Entities.ChatEntity", null)
                        .WithMany()
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Infrastructure.Persistence.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("API.Infrastructure.Persistence.Entities.MessageContentEntity", b =>
                {
                    b.HasOne("API.Infrastructure.Persistence.Entities.MessageEntity", null)
                        .WithOne()
                        .HasForeignKey("API.Infrastructure.Persistence.Entities.MessageContentEntity", "MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("API.Infrastructure.Persistence.Entities.MessageEntity", b =>
                {
                    b.HasOne("API.Infrastructure.Persistence.Entities.ChatEntity", null)
                        .WithMany()
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Infrastructure.Persistence.Entities.MessageEntity", null)
                        .WithMany()
                        .HasForeignKey("ReplyToMessageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("API.Infrastructure.Persistence.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("API.Infrastructure.Persistence.Entities.MessageReadEntity", b =>
                {
                    b.HasOne("API.Infrastructure.Persistence.Entities.MessageEntity", null)
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Infrastructure.Persistence.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
